name: CI

on: 
  push:


jobs:

  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'feelpp/IfcOpenShell' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  build:
    runs-on: self-hosted
    needs: activate
    steps:
    - uses: actions/checkout@v2
#    - name: python
#      run: |
#        python3 mo.py -i data/ifc_files/3pieces_1zone-with-materials-with-sensors.ifc -o data/ifc_files/3pieces_1zone-with-materials-with-sensors
#        cat toto.mo
    - name: Update ubuntu
      run: |
        sudo apt update
        sudo apt-get install git cmake gcc g++ libboost1.67-all-dev python3-all-dev swig libpcre3-dev libxml2-dev
        sudo apt-get install liboce-foundation-dev liboce-modeling-dev liboce-ocaf-dev liboce-visualization-dev liboce-ocaf-lite-dev
    - name: Build ibat
      run: |
        mkdir build && cd build
        cmake \
         -DCMAKE_INSTALL_PREFIX=./install/ \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_PREFIX_PATH=./install/ \
         -DCMAKE_SYSTEM_PREFIX_PATH=./install/ \
         -DOCC_INCLUDE_DIR=/usr/include/oce \
         -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu \
         -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
         -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 \
         -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so \
         -DCOLLADA_SUPPORT=Off \
         -DLIBXML2_INCLUDE_DIR=/usr/include/libxml2 \
         -DLIBXML2_LIBRARIES=/usr/lib/x86_64-linux-gnu/libxml2.so \
         ../cmake
        make -j10
        make install
    - name: Package
      run: |
        make package
      working-directory: build
    - name: Upload 
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ifcos-artifacts
        # Directory containing files to upload
        path: build/assets/ifcos-*

  deliver:
    runs-on: ubuntu-20.04
    needs: build
    name: Docker Build, Tag, Push

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    - name: Download 
      uses: actions/download-artifact@v2
      with:
        # Artifact name
        name: ifcos-artifacts
        path: artifacts/
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1        
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - 
      name: Build container image
      uses: docker/build-push-action@v2
      with: 
        context: artifacts
        repository: feelpp/ifcopenshell
        tags: ghcr.io/feelpp/ifcopenshell:latest
        file: ./Dockerfile
        push: true